name: pages build and deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add concurrency to queue runs instead of canceling them
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false # Set to false to queue runs instead of canceling

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: npm ci # Adjust this based on your project's build setup (e.g., npm, yarn, etc.)

      - name: Build
        run: npm run build # Adjust this to match your build command (e.g., npm run build, yarn build, etc.)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist # Adjust this to the folder where your built files are (e.g., dist, build, etc.)

  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report build status
        run: echo "Build completed successfully"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1